export const PermissionsEnum = [
    {id: 0, value: 'View Only'},
    {id: 1, value: 'Editor'},
    {id: 2, value: 'Creator'}
]

export const RoleEnum = [
    {id: 0, value: 'Root'},
    {id: 1, value: 'Admin'},
    {id: 2, value: 'Standard'},
    {id: 3, value: 'Read Only'}
]


export const TrainingType = [
    {id: 0, value: 'Centralized'},
    {id: 1, value: 'Federated Centralized'},
    {id: 2, value: 'Federated Decentralized'}
]

export const DatasetStatusEnum = [
    {id: 0, value: 'Original'},
    {id: 1, value: 'Unprocessed'},
    {id: 2, value: 'Preprocessing'},
    {id: 3, value: 'Preprocessed'},
    {id: 4, value: 'Extracting features'},
    {id: 5, value: 'Extracted features'}
]

export const UploadTypeEnum = [
    {id: 0, value: 'Autogenerated'},
    {id: 1, value: 'Manual'}
]

export const StatusScenarioEnum = [
    {id: 0, value: 'Deployed'},
    {id: 1, value: 'Finished'},

]



export const StatusModelEnum = [
    {id: 0, value: 'Training'},
    {id: 1, value: 'Trained'},
    {id: 2, value: 'Error'},


]
export const TypeModelEnum = [
    {id: 0, value: 'Classifier'},
    {id: 1, value: 'Anomaly detection'},

]